 name: IcewyndCore
 version: 1.0
 description: Icewynd Core Systems
 author: OnePoundd
 main: Main.Main
 depend: [Factions]
 commands:
    crategive:
    librarian:
    enchanter:
    spawnergive: 
    sandstone:
    xp:
    xpgive:
    ci:
    rules:
    patchnotes:
    ow:
    clearchat:
    ping:
    q:
    msg:
    pinfo:
    msgtoggle:
    nightvision:
      aliases: [nv]
    invsee:
    enderchest:
      aliases: [ec]
    book:
    ban:
    disposal:
    youtube:
    twitch:
    fstats:
    freecam:
    kit:
    event:
    sell:
    shop:
    feed:
    unban:
    help:
    list:
    suicide:
    seen:
    witherspawn:
    reset: